// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for WorkloadType.
const (
	Deployment  WorkloadType = "Deployment"
	StatefulSet WorkloadType = "StatefulSet"
)

// Release defines model for Release.
type Release struct {
	// BoundedContext The bounded context of this release
	BoundedContext *string `json:"boundedContext,omitempty"`

	// Domain The domain of this release
	Domain *string `json:"domain,omitempty"`

	// Id The release identifier
	Id string `json:"id"`

	// InitialDeploymentTime The date and time when this release was initialy deployed
	InitialDeploymentTime *time.Time `json:"initialDeploymentTime,omitempty"`

	// LatestDeploymentTime The date and time when this release was last updated
	LatestDeploymentTime *time.Time `json:"latestDeploymentTime,omitempty"`

	// Name The release name
	Name string `json:"name"`

	// Namespace The namespace where this release is deployed
	Namespace *string `json:"namespace,omitempty"`

	// Status The status of this release
	Status *string `json:"status,omitempty"`

	// Subdomain The subdomain of this release
	Subdomain *string `json:"subdomain,omitempty"`

	// Version The version of this release
	Version   *string    `json:"version,omitempty"`
	Workloads *Workloads `json:"workloads,omitempty"`
}

// Releases defines model for Releases.
type Releases = []Release

// Workload defines model for Workload.
type Workload struct {
	// Annotations The annotations of this workload
	Annotations *map[string]string `json:"annotations,omitempty"`

	// BoundedContext The DDD bounded context this workload is associated to
	BoundedContext *string `json:"boundedContext,omitempty"`

	// CreationTime The creation date and time of the workload
	CreationTime *time.Time `json:"creationTime,omitempty"`

	// Domain The DDD domain this workload is associated to
	Domain *string `json:"domain,omitempty"`

	// Id The workload ID
	Id string `json:"id"`

	// Ingresses The list of ingresses associated with this workload
	Ingresses *[]string `json:"ingresses,omitempty"`

	// Labels The labels of this workload
	Labels *map[string]string `json:"labels,omitempty"`

	// Name The workload name
	Name string `json:"name"`

	// Namespace The namespace this workload is running in
	Namespace *string `json:"namespace,omitempty"`

	// ReleaseName The name of the release this workload is part of
	ReleaseName *string `json:"releaseName,omitempty"`

	// ReleaseVersion The version of the release this workload is part of
	ReleaseVersion *string `json:"releaseVersion,omitempty"`

	// ReplicasDesired The number of replicas desired to be available to users
	ReplicasDesired float32 `json:"replicasDesired"`

	// ReplicasReady The number of replicas available to users
	ReplicasReady float32 `json:"replicasReady"`

	// Status The status of this workload
	Status *string `json:"status,omitempty"`

	// Subdomain The DDD subdomain this workload is associated to
	Subdomain *string `json:"subdomain,omitempty"`

	// Technology The technology used for this workload, taken from the label `app.kubernetes.io/component`
	Technology *string `json:"technology,omitempty"`

	// Type The workload type
	Type WorkloadType `json:"type"`

	// Version The version of this workload
	Version *string `json:"version,omitempty"`
}

// WorkloadType The workload type
type WorkloadType string

// Workloads defines model for Workloads.
type Workloads = []Workload

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetReleasesByName request
	GetReleasesByName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetReleasesByName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReleasesByNameRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetReleasesByNameRequest generates requests for GetReleasesByName
func NewGetReleasesByNameRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/releases/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetReleasesByNameWithResponse request
	GetReleasesByNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetReleasesByNameResponse, error)
}

type GetReleasesByNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Releases
}

// Status returns HTTPResponse.Status
func (r GetReleasesByNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReleasesByNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetReleasesByNameWithResponse request returning *GetReleasesByNameResponse
func (c *ClientWithResponses) GetReleasesByNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetReleasesByNameResponse, error) {
	rsp, err := c.GetReleasesByName(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReleasesByNameResponse(rsp)
}

// ParseGetReleasesByNameResponse parses an HTTP response from a GetReleasesByNameWithResponse call
func ParseGetReleasesByNameResponse(rsp *http.Response) (*GetReleasesByNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReleasesByNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Releases
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
