name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Get branch name
        if: contains(github.event.pull_request.labels.*.name, 'release-integration-sdk-go-build')
        id: branch-name
        uses: tj-actions/branch-names@v7.0.7

      - name: Get development package of release-integration-sdk-go
        if: contains(github.event.pull_request.labels.*.name, 'release-integration-sdk-go-build')
        run: |
          go get -t -u github.com/digital-ai/release-integration-sdk-go@${{ steps. branch-name. outputs. current_branch }}
          go mod tidy

      - name: Build Project
        run: |
          go mod download
          go build

      - name: Run Tests
        run: |
          go test -cover -v ./...
